### PR TITLE
Add bichain & pap

### LINKED ISSUE #2: Add pap
https://github.com/fluture-js/Fluture/pull/404

### LINKED ISSUE #3: Add bichain
https://github.com/fluture-js/Fluture/pull/411

### PR DESCRIPTION
**Pull request by dicearr**
Close #2 and close #3.

_**Note**: If I am not mistaken, this should be released as a breaking change._

### CODE REVIEW

**Comment by Avaq** [comment]
> If I am not mistaken, this should be released as a breaking change.

I think you're right.

**Review by Avaq — APPROVED** [review]

**Comment by wms** [comment]
@Avaq Any chance we can get a new NPM release that includes this addition?

**Comment by Avaq** [comment]
Oh, right! Thanks for the heads-up. I'll do it right away.

**Comment by Avaq** [comment]
@wms Released as 2.0.0

**Pull request merged**
